name: Android CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Check Environment
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Android SDK: $ANDROID_HOME"
          ls -la
          ls -la gradle/wrapper/
          cat settings.gradle
          cat build.gradle
      
      - name: Fix Gradle wrapper
        run: |
          chmod +x ./gradlew
          echo "sdk.dir=$ANDROID_HOME" > local.properties
      
      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace
      
      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk 